version: '3.9'

services:
  gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - sgu-networks

networks:
  sgu-networks:
    external: true
