server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG

common:
  front: http://localhost:3000/, https://sgiufape.vercel.app/
spring:
  application:
    name: sgu-gateway-service
  profiles:
    active: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/sgu-ufape/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: sgu-auth-service
          uri: lb://sgu-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

---
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/sgu-ufape/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: gateway
    prefer-ip-address: false


